import type { Metadata } from "next";
import { Gabarito } from "next/font/google";
import "@/styles/globals.css";
import Navbar from "@/components/Navbar";

const font = Gabarito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={font.className + ' h-screen flex flex-col bg-pattern'}>
        <Navbar />
        <div className="flex-grow">
          {children}
        </div>
        
      </body>
    </html>
  );
}
